// app/(home)/layout.tsx 
import "@/styles/globals.css";

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SideNav from '@/components/Layout/helpers/side-nav';
import MarginWidthWrapper from '@/components/Layout/helpers/margin-width-wrapper';
import Header from '@/components/Layout/helpers/header';
import HeaderMobile from '@/components/Layout/helpers/header-mobile';
import PageWrapper from '@/components/Layout/helpers/page-wrapper';
import Providers from "@/components/Layout/helpers/Providers";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ submenus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className} `}>
        <div className="flex relative">
          <SideNav />
          <main className="flex-1 ">
            <MarginWidthWrapper>
              <Header />
              <HeaderMobile />
              <PageWrapper>
                <Providers>
                  {children}
                </Providers >
              </PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
